#!/bin/bash
# ══════════════════════════════════════════════════════════════════════════
#  load_and_run_edge.sh — Load thin query image + ensure host Ollama
#
#  Usage:
#    ./load_and_run_edge.sh --image ./manual-rag-query.tar.gz --data /path/to/data
# ══════════════════════════════════════════════════════════════════════════

set -euo pipefail

IMAGE_FILE="./manual-rag-query.tar.gz"
DATA_PATH="./data"
HOST_PORT="8000"
COMPOSE_FILE="docker-compose.edge.yml"
IMAGE_TAG="manual-rag-query:latest"
VISION_MODEL="${OLLAMA_VISION_MODEL:-qwen2.5vl:3b}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --image) IMAGE_FILE="$2"; shift 2 ;;
    --data)  DATA_PATH="$2";  shift 2 ;;
    --port)  HOST_PORT="$2";  shift 2 ;;
    --compose) COMPOSE_FILE="$2"; shift 2 ;;
    --help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Manual RAG — Edge Query-Only Load & Run                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Image file   : ${IMAGE_FILE}"
echo "  Data path    : ${DATA_PATH}"
echo "  UI port      : ${HOST_PORT}"
echo "  Vision model : ${VISION_MODEL} (host Ollama)"
echo ""

if ! command -v docker &>/dev/null; then
  echo "✗ Docker not found. Install Docker Desktop / Engine first."
  exit 1
fi

if ! docker info &>/dev/null; then
  echo "✗ Docker daemon is not running. Start Docker and try again."
  exit 1
fi

if ! command -v ollama &>/dev/null; then
  echo "✗ Ollama not found. Install once (needs internet):"
  echo "    https://ollama.com/download"
  exit 1
fi

# Ensure Ollama API is up
if ! curl -sf "http://127.0.0.1:11434/api/tags" >/dev/null 2>&1; then
  echo "▸ Starting ollama serve..."
  ollama serve >/dev/null 2>&1 &
  for i in $(seq 1 30); do
    if curl -sf "http://127.0.0.1:11434/api/tags" >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done
fi

if ! curl -sf "http://127.0.0.1:11434/api/tags" >/dev/null 2>&1; then
  echo "✗ Ollama is not responding at http://127.0.0.1:11434"
  echo "  Open the Ollama app, then retry."
  exit 1
fi

if ! ollama list 2>/dev/null | grep -q "${VISION_MODEL}"; then
  echo "▸ Model ${VISION_MODEL} missing — pulling (one-time; needs internet)..."
  ollama pull "${VISION_MODEL}"
  echo "  ✓ Model ready — later runs can be air-gapped"
else
  echo "  ✓ Host model ${VISION_MODEL} present"
fi

if [ ! -f "${COMPOSE_FILE}" ]; then
  echo "✗ Compose file not found: ${COMPOSE_FILE}"
  echo "  Copy docker-compose.edge.yml next to this script."
  exit 1
fi

if ! docker image inspect "${IMAGE_TAG}" >/dev/null 2>&1; then
  if [ ! -f "${IMAGE_FILE}" ]; then
    echo "✗ Image ${IMAGE_TAG} not loaded and file missing: ${IMAGE_FILE}"
    exit 1
  fi
  echo "▸ Loading image from ${IMAGE_FILE}..."
  docker load < "${IMAGE_FILE}"
  echo ""
fi

# Resolve absolute data path
if [[ "${DATA_PATH}" != /* ]]; then
  DATA_PATH="$(cd "$(dirname "${DATA_PATH}")" 2>/dev/null && pwd)/$(basename "${DATA_PATH}")"
fi
mkdir -p \
    "${DATA_PATH}/chroma_db" \
    "${DATA_PATH}/images" \
    "${DATA_PATH}/manuals"

export HOST_DATA_DIR="${DATA_PATH}"
export API_PORT="${HOST_PORT}"
export EDGE_IMAGE="${IMAGE_TAG}"
export OLLAMA_VISION_MODEL="${VISION_MODEL}"

# OS-safe host mirrors (only paths that exist)
OVERRIDE="docker-compose.edge.override.yml"
{
  echo "# Auto-generated by load_and_run_edge.sh"
  echo "services:"
  echo "  manual-rag:"
  echo "    ports:"
  echo "      - \"${HOST_PORT}:8000\""
  echo "    volumes:"
  echo "      - ${HOST_DATA_DIR}:/app/data"
  for src_dst in \
    "/Users:/host/Users" \
    "/Volumes:/host/Volumes" \
    "/home:/host/home" \
    "/media:/host/media" \
    "/mnt:/host/mnt" \
    "/run/media:/host/run/media"
  do
    src="${src_dst%%:*}"
    dst="${src_dst#*:}"
    if [[ -d "$src" ]]; then
      echo "      - ${src}:${dst}:ro"
    fi
  done
} > "${OVERRIDE}"
echo "  ✓ Wrote ${OVERRIDE}"
echo ""

echo "▸ Starting edge stack (query-only, host Ollama)..."
docker compose -f "${COMPOSE_FILE}" -f "${OVERRIDE}" up -d

echo ""
echo "▸ Waiting for health (up to 180s)..."
HEALTH_WAIT=0
while [ $HEALTH_WAIT -lt 180 ]; do
  STATUS=$(docker inspect --format='{{.State.Health.Status}}' manual-rag-edge 2>/dev/null || echo "starting")
  if [ "$STATUS" = "healthy" ]; then
    break
  fi
  sleep 5
  HEALTH_WAIT=$((HEALTH_WAIT + 5))
  echo "  ... ${HEALTH_WAIT}s — status: ${STATUS}"
done

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  ✓ Edge Manual RAG is running (query-only)              ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Web UI   : http://localhost:${HOST_PORT}"
echo "  Health   : http://localhost:${HOST_PORT}/health"
echo "  Data     : ${HOST_DATA_DIR}"
echo "  Ollama   : host @ 11434 (${VISION_MODEL})"
echo ""
echo "  Stop: docker compose -f ${COMPOSE_FILE} -f ${OVERRIDE} down"
echo ""
