#!/usr/bin/env bash
# Start Manual RAG with a chosen data folder (local path or USB / pendrive).
#
# Usage:
#   ./scripts/run.sh                         # uses ./data
#   ./scripts/run.sh /Volumes/USB/rag-data   # mount USB folder as /app/data
#   ./scripts/run.sh --build /path/to/data   # rebuild image first
#   ./scripts/run.sh --down                  # stop containers

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DO_BUILD=0
DO_DOWN=0
DATA_DIR="./data"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --build) DO_BUILD=1; shift ;;
    --down)  DO_DOWN=1; shift ;;
    --help|-h)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    -*)
      echo "Unknown flag: $1" >&2
      exit 1
      ;;
    *)
      DATA_DIR="$1"
      shift
      ;;
  esac
done

if [[ $DO_DOWN -eq 1 ]]; then
  docker compose down
  exit 0
fi

# Resolve absolute path
if [[ "$DATA_DIR" != /* ]]; then
  DATA_DIR="$(cd "$(dirname "$DATA_DIR")" 2>/dev/null && pwd)/$(basename "$DATA_DIR")"
fi
mkdir -p "$DATA_DIR/manuals" "$DATA_DIR/images" "$DATA_DIR/chroma_db"

export HOST_DATA_DIR="$DATA_DIR"
export OLLAMA_VISION_MODEL="${OLLAMA_VISION_MODEL:-qwen2.5vl:3b}"
export MANUAL_RAG_IN_DOCKER=1

# Only bind-mount host roots that actually exist (avoids compose failures on Linux/macOS)
OVERRIDE="$ROOT/docker-compose.override.yml"
{
  echo "# Auto-generated by scripts/run.sh — do not edit by hand"
  echo "services:"
  echo "  manual-rag:"
  echo "    volumes:"
  echo "      - ${HOST_DATA_DIR}:/app/data"
  for src_dst in \
    "/Users:/host/Users" \
    "/Volumes:/host/Volumes" \
    "/home:/host/home" \
    "/media:/host/media" \
    "/mnt:/host/mnt" \
    "/run/media:/host/run/media"
  do
    src="${src_dst%%:*}"
    dst="${src_dst#*:}"
    if [[ -d "$src" ]]; then
      echo "      - ${src}:${dst}"
    fi
  done
} > "$OVERRIDE"

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Manual RAG — Docker start                               ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo "  Data folder (host): $HOST_DATA_DIR"
echo "  UI / API:           http://localhost:${API_PORT:-8000}"
echo "  Vision model:       ${OLLAMA_VISION_MODEL}"
echo "  Override file:      $OVERRIDE"
echo ""

if [[ $DO_BUILD -eq 1 ]]; then
  echo "▸ Building image (downloads models once — can take a while)..."
  ./scripts/build.sh --model "${OLLAMA_VISION_MODEL}"
fi

if ! docker image inspect manual-rag:latest >/dev/null 2>&1; then
  echo "▸ Image manual-rag:latest not found — building now..."
  ./scripts/build.sh --model "${OLLAMA_VISION_MODEL}"
fi

echo "▸ Starting container..."
docker compose up -d

echo ""
echo "Ready. Open http://localhost:${API_PORT:-8000}/"
echo "Ingest on a strong machine, copy the data folder to USB, then:"
echo "  ./scripts/run.sh /Volumes/YourUSB/rag-data"
echo ""
echo "  Logs:  docker compose logs -f"
echo "  Stop:  ./scripts/run.sh --down"
